# Generated by Django 4.2.2 on 2023-06-14 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product_Category',
            fields=[
                ('Pc_Id', models.IntegerField(primary_key=True, serialize=False)),
                ('Pc_Name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('P_Id', models.IntegerField(primary_key=True, serialize=False)),
                ('P_Name', models.CharField(max_length=100)),
                ('P_Price', models.IntegerField()),
                ('P_Description', models.TextField()),
                ('P_Date', models.DateField()),
                ('Pc_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product_category')),
            ],
        ),
    ]
